services:
  fintechnova.api:
    image: ${DOCKER_REGISTRY-}fintechnovaapi
    build:
      context: .
      dockerfile: FintechNova.API/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Host=ep-noisy-waterfall-amu2xlmh.c-5.us-east-1.aws.neon.tech;Database=neondb;Username=neondb_owner;Password=npg_LhiK0l8HxJZp;SSL Mode=Require;Trust Server Certificate=true;Timeout=30;Command Timeout=60
  db:
    image: postgres:16
    container_name: fintechnova_db_compose
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: fintechnova_db
    ports:
      - "5435:5432"
    volumes:
      - fintechnova_datos:/var/lib/postgresql/data

volumes:
  fintechnova_datos: